require:
  - standard

plugins:
  - standard-performance
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.2

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/integrations/**/*.rb

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/halitosis/rails/**/*.rb

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 7
