name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} and Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby:
          - "3.2.5"
          - "3.3.4"
        rails:
          - "7.1"
          - ""

    env:
      RAILS_VERSION: ${{ matrix.rails }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
